apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: comfyui
  namespace: comfyui
  labels:
    app.kubernetes.io/name: comfyui
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: comfyui
