apiVersion: v1
kind: Service
metadata:
  name: comfyui
  namespace: comfyui
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: comfyui
  ports:
    - name: http
      port: 8188
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: comfyui-lb
  namespace: comfyui
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/component: loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: comfyui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
